# Generated by Django 5.1 on 2024-08-22 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trip',
            name='date',
            field=models.DateField(blank=True),
        ),
        migrations.AlterField(
            model_name='trip',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='trip',
            name='trip_length',
            field=models.IntegerField(blank=True),
        ),
    ]
