# Generated by Django 5.1 on 2024-08-26 15:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_itinerary_trip_itineraries'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trip',
            name='itineraries',
        ),
        migrations.AddField(
            model_name='itinerary',
            name='trip',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='api.trip'),
        ),
    ]
